services:
  productcatalogapi:
    image: productcatalogapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - MongoDB__DatabaseName=productCatalog
    networks:
      - productcatalogapinetwork
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - productcatalogapinetwork

volumes:
  mongo_data:

networks:
  productcatalogapinetwork:
